<a href="https://colab.research.google.com/github/Aaka702/Machine-Learning/blob/main/numpyfunctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#Zero matrix
import numpy as np
x=np.zeros(4,dtype=int)
print(x)
print(x.ndim)

[0 0 0 0]
1


In [8]:
y=np.zeros([2,3,4])
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [9]:
#ones matrix
#1 D ones matrix
z=np.ones(5,dtype=int)
print(z)

[1 1 1 1 1]


In [10]:
#2D  ones matrix
a=np.ones((5,6),dtype=int)
print(a)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [11]:
#Full Matrix

b=np.full([4,3],6)
print(b)

[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]


In [13]:
#Identity Matrix

#1 0 0
#0 1 0
#0 0 1
d=np.identity(3,dtype=int)
print(d)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [19]:
e=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(e)
f=e.reshape(2,6)
print(f)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [21]:
#arange()
g=np.arange(5,9).reshape(2,2)    #arange(start stop step)
g

array([[5, 6],
       [7, 8]])

In [ ]:
#Create a 5x2 matrix using all the multiples of 3 upto 30

In [24]:
k=np.arange(3,31,3).reshape(5,2)
print(k)

[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]
 [27 30]]
