<a href="https://colab.research.google.com/github/Aaka702/Machine-Learning/blob/main/numpyfunctions2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#floor   to remove decimal portion, get previous integer
#[[2.1,3.4,5.6]
#[4.3,3.4,2.1]
#[4.7,3.2,5.4]]
import numpy as np
a=np.array([[2.1,3.4,5.6],[4.3,3.4,2.1],[4.7,3.2,5.4]])
z=np.floor(a)
print(z)

[[2. 3. 5.]
 [4. 3. 2.]
 [4. 3. 5.]]


In [3]:
#Ceil    get next integer

y=np.ceil(a)
print(y)

[[3. 4. 6.]
 [5. 4. 3.]
 [5. 4. 6.]]


In [4]:
b=np.array([[2.1,3.4,5.6],[4.3,3.4,2.1],[4.7,3.2,5.4]])
print(np.round(b))
c=np.array([[1.5,2.5,3.5,4.5,5.5,6.5,7.5]])
print(np.round(c))

[[2. 3. 6.]
 [4. 3. 2.]
 [5. 3. 5.]]
[[2. 2. 4. 4. 6. 6. 8.]]


In [5]:
d=np.array([[3,4,5],[6,7,8],[1,2,9]])
# 3 4 5
# 6 7 8
# 1 2 9

#axis=1 row
#axis=0 column

print(d.max())
print(d.min())
print("Rowwise max element",d.max(axis=1))
print("Columnwise max element",d.max(axis=0))
print("Rowwise max element",d.min(axis=1))
print("Columnwise max element",d.min(axis=0))

9
1
Rowwise max element [5 8 9]
Columnwise max element [6 7 9]
Rowwise max element [3 6 1]
Columnwise max element [1 2 5]


In [6]:
#flatten
b=d.flatten()
print(b)

[3 4 5 6 7 8 1 2 9]


In [7]:
#Sort
a=np.array([1,4,6,3])
b=np.sort(a)
print(b)

[1 3 4 6]


In [8]:
f=np.array([[9,3,2],[1,8,6],[7,5,4]])
# 9 3 2
# 1 8 6
# 7 5 4

print(np.sort(f))   #row wise sort by defualt
print(np.sort(f,axis=0))  #col wise sort

[[2 3 9]
 [1 6 8]
 [4 5 7]]
[[1 3 2]
 [7 5 4]
 [9 8 6]]


In [9]:
e=np.array([[9,3,2],[1,8,6],[7,5,4]])
print(np.argsort(e))


print(np.argsort(e,axis=0))

[[2 1 0]
 [0 2 1]
 [2 1 0]]
[[1 0 0]
 [2 2 2]
 [0 1 1]]


In [10]:
#matrix addition
a=np.array([[1,2],[3,4]])
b=np.array([[3,4],[1,2]])
print(a+b)

[[4 6]
 [4 6]]


In [11]:
#multiplication

print(a.dot(b))

[[ 5  8]
 [13 20]]
